apiVersion: v1
kind: ServiceAccount
metadata:
  name: azdo-sa
  namespace: azdo
  labels:
    env: azdo
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: azdo-secret
  namespace: azdo
  labels:
    env: azdo
  annotations:
    kubernetes.io/service-account.name: azdo-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: azdo
  name: azdo-role
  labels:
    env: azdo
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azdo-rolebinding
  namespace: azdo
  labels:
    env: azdo
subjects:
- kind: ServiceAccount
  name: azdo-sa
  namespace: azdo
  #apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: azdo-role
  apiGroup: rbac.authorization.k8s.io
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: azdo-rolebinding
#   namespace: azdo
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: cluster-admin
# subjects:
# - kind: ServiceAccount
#   name: azdo-sa
#   namespace: azdo