# Service Accounts

# Docs: https://kubernetes.io/docs/concepts/security/service-accounts/

# Commands:

kubectl create serviceaccount <saname> # Each namespace has it's own default SA. Use kubectl create token <saname> to create a token on-demand.
kubectl get/describe serviceaccount <saname> # Token name is also described.
kubectl get/describe secret <saname-token-abcde>

kubectl get secret <saname>-secret -o jsonpath='{.data.token}' | base64 --decode

# Example: Creates a Secret object with a Token for the SA that can then be used by a Pod

apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: <saname>-secret
  annotations:
    kubernetes.io/service-account.name: <saname> # Associate object with the Service Account.
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    stdin: true
    tty: true
  serviceAccountName: <saname>
  automountServiceAccountToken: false
