apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bg
  name: blue-deployment
  labels:
    app: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "16Mi"
            cpu: "50m"
          limits:
            memory: "32Mi"
            cpu: "100m"
        lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "echo 'BLUE DEPLOYMENT' > /usr/share/nginx/html/index.html"]
      nodeSelector:
        agentpool: user